### ISSUE TITLE
Deployment failed for PR 195

### ISSUE THREAD

**Issue by mpomarlan** [ease-crc/soma#196] opened 2021-11-02 14:43 UTC
I doubt this has anything to do with the PR contents though. The reported errors are

Path does not exist /home/runner/work/soma/soma/build/metrics.json

Exit code 1 returned from process: file name '/home/runner/runners/2.283.3/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

**Comment by mpomarlan** [comment] 2021-11-02 15:03
More info on the error I think can be found in the log of the onto metrics script:

Run sudo ./scripts/OntoMetrics.sh $GITHUB_WORKSPACE/build/SOMA.owl $GITHUB_WORKSPACE/build
./scripts
fetching result from https://ontometrics.informatik.uni-rostock.de
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  470k  100  4514  100  465k   2969   306k  0:00:01  0:00:01 --:--:--  309k
writing metrics.xml
curl: try 'curl --help' or 'curl --manual' for more information
writing metrics.json
Traceback (most recent call last):
  File "./scripts/xml2json.py", line 249, in <module>
    main()
  File "./scripts/xml2json.py", line 237, in main
    out = xml2json(input, options, strip_ns, strip)
  File "./scripts/xml2json.py", line 176, in xml2json
    elem = ET.fromstring(xmlstring)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
writing metrics.js
cat: /home/runner/work/soma/soma/build/metrics.json: No such file or directory

**Comment by daniel86** [comment] 2022-03-23 12:53
well it seems curl is not happy with some of its arguments. but I do not know what the problem is, what has changed? a different curl version used in CI? must be it or? else it wouldn't make sense that it starts complaining without the script changing

**Comment by daniel86** [comment] 2022-03-23 12:54
here is the script BTW: https://github.com/ease-crc/soma/blob/master/scripts/OntoMetrics.sh

**Comment by sasjonge** [comment] 2022-03-24 11:52
I contacted the authors from OntoMetrics, and found out that the endpoint changed. Additionally the current endpoints don't completly work for our use case at the moment (curl POST commands are blocked by their firewall), but they said they will fix it, so I would wait for some days.

**Comment by daniel86** [comment] 2022-03-28 10:49
fixed in https://github.com/ease-crc/soma/pull/204

**Comment by sasjonge** [comment] 2022-04-11 13:49
This should have been fixed with the PR and fixed it on my fork of SOMA, but the call the OntoMetrics doesn't work for me.

**Comment by sasjonge** [comment] 2022-05-20 11:27
The deployment is now fixed

**Closed by sasjonge** 2022-05-20 11:27 UTC
Labels: error
