### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#305] opened 2023-07-28 11:02 UTC
The SOMA vocabulary job fails. Seems like we need to convert the functional syntax to a format that owlready2 can read for that.

**Comment by daniel86** [comment] 2024-05-08 12:13
This is really something that should be fixed. @mrnolte if it is caused by your change, I think you should take care fixing it. There were already a few people trying to access the doc. It is also referenced in papers, so better to make the link working again!

**Comment by mrnolte** [comment] 2024-05-14 09:02
I am happy to have a look at the issue, but cannot see how this would be my fault -- the change was discussed in the SOMA meeting and agreed upon by everyone, including you @daniel86, to make commit changes more readable for reviewers.

**Comment by daniel86** [comment] 2024-05-14 11:24
yes @mrnolte but agreeing on a change does not imply to ignore problems caused by the change. If I remeber correctly then you made the suggestion and were the lead in doing the change, hence imo it is your sphere of responsibility to take care that all problems caused by the change are fixed. It is clear that you not always see all implications of a change, so such situations happen. Still the person leading and pushing the change is imo main responsible person for all the problems caused by it

**Comment by mrnolte** [comment] 2024-05-15 12:45
Still I think it is best to have the original developers have a look at stuff. For example, when a team decides to make database changes, the back-end developer would adapt the back-end instead of the database developer, because he is familiar with it. I have not worked with the documentation before.

**Closed** 2024-05-17 07:17 UTC
Labels: error
